### ISSUE TITLE
update era5 daily yml entry in next release

### ISSUE THREAD

**Issue by laurenebouaziz** [DirkEilander/hydromt-artifacts#1]
as discussed with @hboisgon :

the resampled daily era5 files are updated on the p drive in the directory "daily_merged":
- resampled without scale and offset 
- offset already applied in the resampling
- precipitation saved as mm/d instead of m/d

this leads to a change in the yml file for era5 daily

- path
- offset
- unit conversion 

file is attached in the zip.

to be included in the next release in combination with previous changes made for the soilgrids2 changes (see version v0.0.5 as also previously shared with @hboisgon, too large to include here) 
 
[data_sources_deltares_era5.zip](https://github.com/DirkEilander/hydromt-artifacts/files/6908436/data_sources_deltares_era5.zip)

**Comment by DirkEilander** [comment]
Thanks @laurenebouaziz ! I've added the data_sources_deltares.yml file to the repos (before it was only in the release files). Could you include your update in this file and commit and push your changes? In this way we also keep a reversion of this file.

We can also update the current version of the yml file if the updates do not require a new hydromt version. Although this would mean that the artifacts might be slightly different from the Deltares data, which is not a big issue I think. What do you think @hboisgon ?

**Comment by hboisgon** [comment]
It's much better indeed to add the data_sources_deltares.yml to the repos directly! Makes it much easier to update and track changes.

@DirkEilander I think from now on we can indeed separate the Deltares data from the artifacts store. The artifacts are created for demo purpose, so you just need to be able to build/update demo models from it. So when we add new models, we may need to add new data to the artifacts but not everything needs to be in.

**Comment by laurenebouaziz** [comment]
@DirkEilander can you give me the rights to edit and push changes to this repos?
I now created a fork, but this can't be pull requested to your main, it seems....

**Comment by DirkEilander** [comment]
@laurenebouaziz I'm surprised you can't make a PR from a fork - can't find a specific setting for this. 
I've now invited you as collaborator on this repos which should hopefully give you rights to work in the repos directly (and to make the PR from the fork I guess).

**Comment by DirkEilander** [comment]
Thanks for the PR @laurenebouaziz. I've also updated the release artifacts. De era5 key should now refer to your updated version in hydromt.

**Comment by laurenebouaziz** [comment]
perfect! thanks @DirkEilander
